version: '3.8'

services:
  app:
    build: .
    ports:
      - "7997:7997"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/data.db
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
